app:
  grpc-gateway-port: 8090
  host: localhost
  port: 8080
  env: local
db:
  host: localhost
  port: 5432
  user: postgres
  password: password
  dbname: local
  sslmode: disable
token:
  access_token_private_key: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlCT2dJQkFBSkJBTkpZU1VGRUcvV3RNT1NlSW11WHBDZlNac1dCVnhqS1JwaUlhc2x1ZEVwaXdzMTM4eHRUCjNlYzhTbDBmdVZTcVNnS0UwdzkxWDFZMTYrckVwZXRDbzEwQ0F3RUFBUUpBQXNyVlBoNlBXSFdTSHBiUzBpYlQKTVF3ai9SODRic1hRcGhtNWdTOE1NQ2lWU3FWZ01idTJSeFFDQmlxdS9JYUlLcHRDL3dwSmR0WG9uV1c3blU5egpnUUloQVB4aGdSUlFTRG8xRzIwTExEQXpJYzdvYVFnSlkxcXRlTWVEZERydDREZHhBaUVBMVZ4M2dYdWY4STY3CjU5eWhaT0JaeVFuTWRqQ25XYW1EQ3Jhby9Bc3g3SzBDSVFETVRpNU5BSFNIMGtnQ2JRSDNmdDBHZnpQUFVySkEKVEoreWV5TFROWS9Gc1FJZ0htTTdDaEFIYVlXS3NhMDB0MTlVcWxOZzhYeGdlVjZ4TVRkdXZlY0NSMGtDSUhjZwpxTU5EK1M5VXdXTmlHWGMxMXlzZmZqWThGMjVTQ0FBaHcxOGVxTVFxCi0tLS0tRU5EIFJTQSBQUklWQVRFIEtFWS0tLS0t
  access_token_public_key: LS0tLS1CRUdJTiBQVUJMSUMgS0VZLS0tLS0KTUZ3d0RRWUpLb1pJaHZjTkFRRUJCUUFEU3dBd1NBSkJBTkpZU1VGRUcvV3RNT1NlSW11WHBDZlNac1dCVnhqSwpScGlJYXNsdWRFcGl3czEzOHh0VDNlYzhTbDBmdVZTcVNnS0UwdzkxWDFZMTYrckVwZXRDbzEwQ0F3RUFBUT09Ci0tLS0tRU5EIFBVQkxJQyBLRVktLS0tLQ==
